### ISSUE TITLE
aplore3. ICU dataset

### ISSUE THREAD

**Issue by SunsetBlvd** [lbraglia/aplore3#2]
There is an error in ICU dataset. In icu$sta dead people should be coded as 1 and alive people as 0. So, there should be 160 alive and 40 dead people. Check coding in paper book. Probably you took coding from pdf-file accompanying paper book and it seems like it has typo.

**Comment by lbraglia** [comment]
The pdf-file accompanying the paper book

https://github.com/lbraglia/aplore3/blob/master/rawdata/ICU/ICU_Data_Code_Sheet.pdf

is coherent with the printed book (3rd edition, page 23, 0 = Died, 1 = Lived) that, in turn, is coherent with what I've coded to import the dataset

https://github.com/lbraglia/aplore3/blob/master/rawdata/icu.R#L21

Why do you say that the alives should be 160?

**Comment by SunsetBlvd** [comment]
![pic2_zpsb6mxgshd](https://cloud.githubusercontent.com/assets/603306/18830641/d9ff1b68-83e1-11e6-8219-29345434302c.png)

**Comment by lbraglia** [comment]
ok, for the sake of completeness this is from the third edition..

![20160926_120035](https://cloud.githubusercontent.com/assets/603306/18830668/0527198a-83e2-11e6-854b-aed2e697fd60.jpg)

I'll check the mismatch with the authors ASAP

**Comment by lbraglia** [comment]
Prof. Hosmer confirmed that there should be 160 alive and 40 dead people.

I'll fix it ASAP.

**Comment by SunsetBlvd** [comment]
Where was your book printed?

![pic1](http://i1026.photobucket.com/albums/y326/ConcertoForCello/3ed1_zpsr4ispja3.jpg)

![pic2](http://i1026.photobucket.com/albums/y326/ConcertoForCello/3ed2_zps7db4fipb.jpg)

**Comment by lbraglia** [comment]
USA

![20160929_104455](https://cloud.githubusercontent.com/assets/603306/18947196/590bc7e2-8632-11e6-8f8a-eafba8668af4.jpg)

however mine is 1st printing, yours is 5th

https://en.wikipedia.org/wiki/Printer's_key

**Comment by lbraglia** [comment]
uploaded to CRAN, should be available asap
